"""Browser-based compatibility client for user-triggered browser flows.

stoken can be generated by the browser's JS environment when a user-initiated
login flow needs compatibility help. Low-Risk Assistance Mode blocks sensitive
automation such as outreach, bulk actions, risk-control retries, and candidate
personal-data workflows before they reach this client.

Supports two modes:
  1. CDP mode: connects to user's existing Chrome via DevTools Protocol
  2. Patchright mode (fallback): launches a headless Chromium instance
"""

import sys
import time
from pathlib import Path
from types import TracebackType
from typing import Any, cast
from urllib.parse import urlparse

from patchright.sync_api import sync_playwright

from boss_agent_cli.api import endpoints
from boss_agent_cli.api.browser_source import (
	CHANNEL_BRIDGE,
	CHANNEL_CDP,
	CHANNEL_HEADLESS,
	BrowserSourcePolicy,
	BrowserSourceUnavailable,
	resolve_policy,
)
from boss_agent_cli.api.throttle import RequestThrottle
from boss_agent_cli.auth.browser import _DEFAULT_CDP_URL as CDP_DEFAULT_URL

HOME_URL = "https://www.zhipin.com/"
_ZHIPIN_HOST = "zhipin.com"


def _is_zhipin_url(url: str) -> bool:
	"""精确 hostname 校验：仅 zhipin.com 或其子域名视为 BOSS 直聘页面。

	刻意不用 ``"zhipin.com" in url`` 子串判断——伪造 host（如
	``zhipin.com.evil.example``）或带该域名的查询串都能骗过子串检查
	（CodeQL ``py/incomplete-url-substring-sanitization``）。
	"""
	host = urlparse(url).hostname
	if host is None:
		return False
	host = host.rstrip(".").lower()
	return host == _ZHIPIN_HOST or host.endswith(f".{_ZHIPIN_HOST}")


def _find_reusable_zhipin_page(context: Any) -> Any | None:
	"""在用户 context 已打开的页面里找第一个 zhipin 页复用，找不到返回 None。"""
	for page in getattr(context, "pages", None) or []:
		if _is_zhipin_url(getattr(page, "url", "")):
			return page
	return None


class RecruiterChatTabRequired(RuntimeError):
	"""招聘者操作（issue #217 修复路径）需要用户已打开 chat/index 页。

	不自动新开 tab：避免替用户改变官方页面状态或触发额外平台风险信号。
	友好做法是返回明确指引，让用户自己打开。
	"""

	def __init__(self) -> None:
		super().__init__(
			"recruiter chat tab not found in CDP Chrome — "
			"please open https://www.zhipin.com/web/chat/index in your "
			"Chrome (CDP-attached) and retry."
		)


# 超时常量
_CDP_PROBE_TIMEOUT = 3  # 显式 --cdp-url 的 CDP 探测 HTTP 超时（秒）
_CDP_AUTO_PROBE_TIMEOUT = 1  # 默认自动探测 localhost:9222 的超时（无调试端口时快速失败，省 ~2s）
_NAV_TIMEOUT_MS = 15000  # 页面导航超时（毫秒）
# zhipin 首页常驻请求多、headless 下基本进不了 networkidle；domcontentloaded 后 JS
# 环境即可发 fetch，故宽限缩到 0.8s（实测每次都会耗满，缩短直接省 ~2s/搜索）。
_HEADLESS_NETWORKIDLE_GRACE_MS = 800

# macOS / Linux / Windows Chrome user data 默认路径
_CHROME_USER_DATA_CANDIDATES = [
	Path.home() / "Library/Application Support/Google/Chrome",  # macOS
	Path.home() / ".config/google-chrome",  # Linux
	Path.home() / "AppData/Local/Google/Chrome/User Data",  # Windows
]


class BrowserSession:
	"""Persistent browser session that makes API calls via page.evaluate(fetch).

	Tries CDP connection to user's Chrome first; falls back to headless patchright.
	"""

	def __init__(
		self,
		cookies: dict[str, Any],
		user_agent: str,
		*,
		delay: tuple[float, float] = (1.5, 3.0),
		cdp_url: str | None = None,
		logger: Any = None,
		browser_source: str | None = None,
	) -> None:
		self._throttle = RequestThrottle(delay)
		# patchright / BridgeClient 运行时创建；注解为 Any 让 mypy 对外部依赖放行
		self._pw: Any = None
		self._browser: Any = None
		self._context: Any = None
		self._page: Any = None
		self._cookies = cookies
		self._user_agent = user_agent
		self._started = False
		self._cdp_url = cdp_url
		self._is_cdp = False
		self._own_context = False  # 是否由我们创建的 context（需要在 close 时清理）
		self._own_page = True  # 是否由我们新建的 page（复用用户已开页签时为 False，close 不关它）
		self._logger = logger
		self._bridge_client: Any = None
		self._is_bridge = False
		# 通道来源策略 —— 本类上**唯一**的来源/模式选择器。
		# 禁止再加第二个模式布尔：那正是 #404 与 #388 各插一个短路、
		# git 干净自动合并却留下两个互不感知开关的成因（见 browser_source 模块文档）。
		# 门禁 test_browser_session_has_exactly_one_source_selector 守住这一点。
		self._policy: BrowserSourcePolicy = resolve_policy(browser_source)

	def _log(self, message: str) -> None:
		"""Diagnostic channel logs: debug by default so TTY wizard stays clean."""
		if self._logger is not None:
			debug = getattr(self._logger, "debug", None)
			if callable(debug):
				debug(message)
				return
			info = getattr(self._logger, "info", None)
			if callable(info):
				# Only when logger has no debug API — keep quiet if level is error default.
				info(message)
				return
		import os

		if os.environ.get("BOSS_BROWSER_VERBOSE", "").strip() in {"1", "true", "yes", "on"}:
			print(message, file=sys.stderr)

	def _ensure_started(self) -> None:
		"""按 policy 声明的通道白名单依次尝试；耗尽即按 policy fail-closed。

		这是**唯一**的通道分发点。禁止在本方法里写 ``if self._policy.name == X``
		式的策略分支——顺序与准入全部来自 ``policy``，新增来源只加表里一行。
		门禁 ``test_dispatcher_has_no_policy_name_branch`` 守住这一点。
		"""
		if self._started:
			return

		policy = self._policy
		attempted: list[str] = []
		try:
			for channel in policy.channels:
				attempted.append(channel)
				if channel == CHANNEL_BRIDGE:
					# fail-closed 语义：_try_bridge 内部 except → False，从不抛。
					# 失败 = 继续白名单里的下一个通道；白名单耗尽不降级。
					if self._try_bridge():
						return
				elif channel == CHANNEL_CDP:
					# 惰性起 driver：stored-cookie 这类不含 headless 的来源，
					# CDP 失败时不该白留一个 playwright driver 进程。
					self._ensure_playwright()
					if self._try_cdp():
						return
				elif channel == CHANNEL_HEADLESS:
					self._ensure_playwright()
					# _start_headless 成功即置 _started，失败抛 playwright 原生异常
					# 并原样上抛（→ display 兜底 NETWORK_ERROR）。这一支只出现在
					# auto 的链尾，是「默认行为一字不改」的落点。
					self._start_headless()
					return
				else:  # pragma: no cover - 由门禁 test_every_declared_channel_is_dispatchable 拦住
					raise ValueError(f"unknown channel {channel!r} in policy {policy.name!r}")
		except BaseException:
			# 修既有缺陷：_start_headless / sync_playwright().start() 抛错时
			# self._pw 已启动却永远不会 stop()，下次 request() 会再起一个 driver 进程。
			self._release_playwright()
			raise

		# ── 通道耗尽 ──
		# auto 到不了这里（headless 支要么 return 要么抛）。
		self._release_playwright()
		if not policy.fail_closed:  # pragma: no cover - 防御：非 auto 但没声明 failure_code
			raise RuntimeError(f"browser source {policy.name!r} exhausted without a failure_code")
		raise BrowserSourceUnavailable(policy, tuple(attempted))

	def _ensure_playwright(self) -> None:
		if self._pw is None:
			self._pw = sync_playwright().start()

	def _release_playwright(self) -> None:
		if self._pw is not None:
			try:
				self._pw.stop()
			except Exception:
				pass
			self._pw = None

	def _try_bridge(self) -> bool:
		"""尝试通过 Browser Bridge（Chrome 扩展 + daemon）连接。"""
		try:
			from boss_agent_cli.bridge.client import BridgeClient

			client = BridgeClient()
			if not client.is_running():
				return False
			if not client.is_extension_connected():
				self._log("[boss] Bridge daemon 运行中但扩展未连接")
				return False
			self._bridge_client = client
			self._started = True
			self._is_cdp = False
			self._is_bridge = True
			self._log("[boss] Bridge 模式连接成功（Chrome 扩展 + daemon）")
			return True
		except Exception:
			return False

	def _try_cdp(self) -> bool:
		"""Try connecting to user's Chrome via CDP.

		Attempts in order:
		  1. Explicit cdp_url if provided
		  2. Default http://localhost:9222 (+ auto WS fallback)   ← 仅当 policy.auto_probe_cdp
		  3. WebSocket URL from Chrome's DevToolsActivePort file   ← 同上

		``auto_probe_cdp=False`` 的来源只连用户显式给的 ``--cdp-url``，
		让「指定 CDP」名副其实；没给地址就直接失败，不静默连到别的浏览器。
		"""
		policy = self._policy
		# (url, 是否为用户显式指定) —— 显式与否决定能否新建 context 注入凭据
		urls_to_try: list[tuple[str, bool]] = []
		if self._cdp_url:
			urls_to_try.append((self._cdp_url, True))
		if policy.auto_probe_cdp:
			urls_to_try.append((CDP_DEFAULT_URL, False))

			# 从 DevToolsActivePort 文件读取 WebSocket URL
			ws_url = self._read_devtools_active_port()
			if ws_url:
				urls_to_try.append((ws_url, False))

		for url, explicit in urls_to_try:
			if self._try_connect(url, explicit=explicit):
				return True
			# HTTP URL 连接失败时，尝试从 /json/version 获取 WS URL。
			# 仅对用户显式提供的 --cdp-url 用较长超时；默认 localhost:9222 自动探测
			# 用短超时快速失败（无调试端口时避免白等 ~2s）。
			if url.startswith("http"):
				probe_timeout = _CDP_PROBE_TIMEOUT if url == self._cdp_url else _CDP_AUTO_PROBE_TIMEOUT
				ws = self._fetch_ws_url(url, timeout=probe_timeout)
				if ws and self._try_connect(ws, explicit=explicit):
					return True
		return False

	def _try_connect(self, url: str, *, explicit: bool = True) -> bool:
		"""Attempt a single CDP connection, reusing user's existing context.

		Reuses the first existing browser context to preserve the user's
		login state and avoid creating extra browser state. Only creates a
		new context when none exists.
		"""
		try:
			self._browser = self._pw.chromium.connect_over_cdp(url)
			contexts = self._browser.contexts

			if contexts:
				# 复用用户现有 context（保留登录态，避免额外浏览器状态）
				self._context = contexts[0]
				self._own_context = False  # 非我们创建，close 时不关闭
				# 优先复用用户已打开的 zhipin 页签：避免每次高风险 op 都新开空白页 +
				# 导航到 BOSS 首页（issue #334：用户观感是"反复自动新开/刷新页面"），
				# 同时降低自动化足迹。请求只需 page 处于 zhipin 同源即可携带 cookie。
				reused = _find_reusable_zhipin_page(self._context)
			elif not self._policy.may_create_context or not explicit:
				# fail-closed：不在用户浏览器里新建 context 注入本地 Cookie。
				# Issue #387 把「把 Cookie 复制到另一个 Profile」列为反面方案
				# （凭据暴露 + 会话竞争）。`explicit` 守卫另挡一种情况：自动探测到的
				# 端点可能是任何在 9222 上监听的 Chromium（其他 Electron 应用、
				# 用户自己起的隔离 profile），不该被当成用户会话注入 wt2/at。
				self._log(f"[boss] CDP ({url}) 无可复用 context，按 browser-source={self._policy.name} 拒绝新建")
				self._close_browser_quietly()
				return False
			else:
				# 没有已存在 context，创建新的并注入 cookies
				self._context = self._browser.new_context()
				if self._cookies:
					self._context.add_cookies(
						[
							{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
							for name, value in self._cookies.items()
						]
					)
				self._own_context = True
				reused = None

			if reused is not None:
				# 复用已打开的 zhipin 页签：不新建 page、不导航，close 时也不关它
				self._page = reused
				self._own_page = False
				page_label = "复用已打开 zhipin 页签"
			elif not self._policy.use_stored_credentials:
				# existing-browser 不读取本地凭据，也不得在用户 context 里新建页面
				# 再导航到目标站点。没有已打开的 zhipin 页签就视为该候选不可用，
				# 继续策略表中的下一个通道，最终按 policy fail-closed。
				self._log(f"[boss] CDP ({url}) 未找到已打开的 zhipin 页签，拒绝导航用户浏览器")
				self._close_browser_quietly()
				return False
			else:
				self._page = self._context.new_page()
				self._own_page = True
				# CDP 模式下用较长超时 + DOM 就绪等待（commit 级返回后立即
				# evaluate 会撞上 execution context destroyed）
				try:
					self._page.goto(HOME_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
				except Exception:
					pass  # 即使导航超时，页面 JS 环境已可用
				page_label = "新建 page"
			self._started = True
			self._is_cdp = True
			reuse_label = "复用用户 context" if not self._own_context else "新建 context"
			self._log(f"[boss] CDP 连接成功 ({url})，{reuse_label} + {page_label}")
			return True
		except Exception:
			self._close_browser_quietly()
			return False

	def _close_browser_quietly(self) -> None:
		"""关掉本次 connect_over_cdp 建立的 browser 句柄，失败静默。

		只断开我们这一侧的连接，不影响用户浏览器本身。
		"""
		if self._browser:
			try:
				self._browser.close()
			except Exception:
				pass
			self._browser = None
		self._context = None

	@staticmethod
	def _fetch_ws_url(http_url: str, timeout: float = _CDP_PROBE_TIMEOUT) -> str | None:
		"""Fetch WebSocket debugger URL from Chrome's /json/version endpoint."""
		import httpx

		try:
			resp = httpx.get(f"{http_url}/json/version", timeout=timeout)
			payload = resp.json()
			if not isinstance(payload, dict):
				return None
			return cast("str | None", payload.get("webSocketDebuggerUrl"))
		except (httpx.HTTPError, ValueError, KeyError):
			return None

	@staticmethod
	def _read_devtools_active_port() -> str | None:
		"""Read Chrome's DevToolsActivePort file to get WS endpoint."""
		for user_data_dir in _CHROME_USER_DATA_CANDIDATES:
			port_file = user_data_dir / "DevToolsActivePort"
			if port_file.exists():
				try:
					lines = port_file.read_text().strip().splitlines()
					if len(lines) >= 2:
						port = lines[0].strip()
						ws_path = lines[1].strip()
						return f"ws://127.0.0.1:{port}{ws_path}"
				except Exception:
					continue
		return None

	def _start_headless(self) -> None:
		"""Fallback: launch headless patchright Chromium."""
		self._browser = self._pw.chromium.launch(headless=True)
		self._context = self._browser.new_context(
			user_agent=self._user_agent,
			viewport={"width": 1280, "height": 800},
			locale="zh-CN",
			timezone_id="Asia/Shanghai",
		)
		self._own_context = True
		self._own_page = True
		self._context.add_cookies(
			[
				{"name": name, "value": value, "domain": ".zhipin.com", "path": "/"}
				for name, value in self._cookies.items()
			]
		)
		self._page = self._context.new_page()
		self._page.goto(HOME_URL, wait_until="domcontentloaded", timeout=_NAV_TIMEOUT_MS)
		try:
			self._page.wait_for_load_state("networkidle", timeout=_HEADLESS_NETWORKIDLE_GRACE_MS)
		except Exception as e:
			# zhipin 首页常驻请求较多，headless 模式下不一定能进入 networkidle；
			# 页面 JS 环境已可用时，继续直接发起 fetch 请求更稳。
			self._log(f"[boss] headless 首页未进入 networkidle（{e}），继续直接发起请求")
		self._started = True
		self._is_cdp = False
		self._log(
			"[boss] CDP 不可用（提示：需以 --remote-debugging-port=9222 启动 Chrome），降级到 headless patchright"
		)

	# ── Core request via browser fetch() ─────────────────────────────

	def request(
		self, method: str, url: str, *, params: dict[str, Any] | None = None, data: dict[str, Any] | None = None
	) -> dict[str, Any]:
		self._ensure_started()
		self._throttle.wait()

		referer = endpoints.REFERER_MAP.get(url, f"{endpoints.BASE_URL}/")

		# Bridge 模式：通过扩展 fetch
		if self._is_bridge and self._bridge_client:
			import urllib.parse

			full_url = url
			if params:
				full_url = f"{url}?{urllib.parse.urlencode(params)}"
			try:
				result = self._bridge_client.fetch_json(
					full_url,
					method=method,
					data=data,
					referer=referer,
				)
			except Exception as exc:
				# Bridge 的连接布尔不证明 workspace/目标页可用。显式来源下把
				# 这种会话级失败归入来源契约；auto 仍保留原异常 → NETWORK_ERROR。
				if self._policy.fail_closed:
					raise BrowserSourceUnavailable(
						self._policy,
						(CHANNEL_BRIDGE,),
						detail="Bridge 已连接但现有页面会话不可用",
					) from exc
				raise
			self._throttle.mark()
			return cast("dict[str, Any]", result)

		# Playwright 模式（CDP 或 headless）
		result = self._page.evaluate(
			"""
			async ({method, url, params, data, referer}) => {
				try {
					let fetchUrl = url;
					if (params && Object.keys(params).length > 0) {
						const sp = new URLSearchParams();
						for (const [k, v] of Object.entries(params)) {
							if (v !== null && v !== undefined) sp.append(k, String(v));
						}
						fetchUrl = url + '?' + sp.toString();
					}

					const options = {
						method: method,
						credentials: 'include',
						headers: {
							'Accept': 'application/json, text/plain, */*',
							'Referer': referer,
							'X-Requested-With': 'XMLHttpRequest',
						},
					};

					if (method === 'POST' && data) {
						options.headers['Content-Type'] = 'application/x-www-form-urlencoded';
						const formData = new URLSearchParams();
						for (const [k, v] of Object.entries(data)) {
							formData.append(k, String(v));
						}
						options.body = formData.toString();
					}

					const resp = await fetch(fetchUrl, options);
					return await resp.json();
				} catch (e) {
					return {code: -1, message: e.message, zpData: {}};
				}
			}
		""",
			{"method": method, "url": url, "params": params or {}, "data": data, "referer": referer},
		)

		self._throttle.mark()
		return cast("dict[str, Any]", result)

	# ── Arbitrary JS evaluation (CDP-only, raw websocket) ────────────

	def evaluate_js(self, script: str, arg: Any = None) -> Any:
		"""Run JS in the user's recruiter chat tab via raw CDP websocket.

		Required for recruiter send_message (issue #217): we reach into the
		招聘者 chat page's Vue 2 instance to call geek-list.geekClick() +
		editor.sendText(). The normal BrowserSession.request fetch path can't
		do that — it runs JS in a blank tab BrowserSession owns, not in the
		user's recruiter tab.

		Why raw CDP instead of patchright: attaching patchright to another
		tab we didn't create via new_page() triggers 'Frame was detached'
		errors when that page navigates or re-renders (Vue SFC rebuilds
		frame tree). Raw CDP is a stateless RPC — we just send
		Runtime.evaluate and read the result, no session book-keeping.

		Intentionally does NOT call _ensure_started(): patchright's
		connect_over_cdp enumerates every tab's frame tree on attach, which
		can race with Vue re-renders on the recruiter page and crash the
		Node driver before we even get to our evaluate call. evaluate_js
		only needs the CDP HTTP endpoint reachable — not patchright.

		Only works in CDP mode (user has chrome://<devtools port>/json
		reachable and the recruiter chat tab open). Bridge/headless modes
		have no access to the user's Vue runtime.
		"""
		if self._is_bridge:
			raise RuntimeError("evaluate_js requires CDP mode (bridge mode has no access to user Chrome)")
		self._require_cdp_source("evaluate_js")
		cdp_url = self._cdp_url or CDP_DEFAULT_URL
		return _cdp_evaluate_in_chat_tab(cdp_url, script, arg)

	def evaluate_js_with_chat_events(self, script: str, arg: Any = None, *, listen_ms: int = 3000) -> dict[str, Any]:
		"""Run JS in the recruiter chat tab and collect short-lived chat WS events.

		Used by recruiter send_message verification to distinguish a real chat send
		from UI-only draft mutation or suggestion traffic.
		"""
		if self._is_bridge:
			raise RuntimeError(
				"evaluate_js_with_chat_events requires CDP mode (bridge mode has no access to user Chrome)"
			)
		self._require_cdp_source("evaluate_js_with_chat_events")
		cdp_url = self._cdp_url or CDP_DEFAULT_URL
		return _cdp_evaluate_with_chat_events_in_chat_tab(cdp_url, script, arg, listen_ms=listen_ms)

	def _require_cdp_source(self, api: str) -> None:
		"""裸 CDP 路径的来源守卫。

		``evaluate_js`` 系列刻意绕过 ``_ensure_started``（见上方 docstring：
		patchright 附着别人的 tab 会撞 'Frame was detached'），所以它不受
		分发器约束——这是本类最大的 fail-open 面：一个禁用了 CDP 的来源，
		在这条路上照样会直连 ``CDP_DEFAULT_URL``。此处补上等价守卫。
		"""
		if not self._policy.allows(CHANNEL_CDP):
			raise BrowserSourceUnavailable(
				self._policy,
				(CHANNEL_CDP,),
				detail=f"{api} 需要 CDP 通道，而 browser-source={self._policy.name} 不允许",
			)
		if not self._policy.auto_probe_cdp and not self._cdp_url:
			raise BrowserSourceUnavailable(
				self._policy,
				(CHANNEL_CDP,),
				detail=f"{api} 需要显式 --cdp-url（browser-source={self._policy.name} 不自动探测端点）",
			)

	# ── Lifecycle ────────────────────────────────────────────────────

	@property
	def is_cdp(self) -> bool:
		"""Whether this session is using CDP connection to user's Chrome."""
		return self._is_cdp

	def close(self) -> None:
		if not self._started:
			# 已关闭 / 从未成功启动：只确保 driver 不泄漏，不重复拆卸。
			# 真正的幂等守卫——否则第二次 close 会因为 _reset_channel_state 已把
			# _is_cdp 置 False 而走进 headless 分支，对一个 CDP 会话执行错误的拆卸。
			self._release_playwright()
			return

		if self._is_bridge and self._bridge_client:
			try:
				self._bridge_client.close_window()
			except Exception:
				pass
			self._bridge_client = None
			self._reset_channel_state()
			return

		if self._is_cdp:
			# CDP 模式：只关闭我们新建的 page 和 context，不动用户浏览器或已复用的页签
			if self._page and self._own_page:
				try:
					self._page.close()
				except Exception:
					pass
			if self._own_context and self._context:
				try:
					self._context.close()
				except Exception:
					pass
		else:
			# Headless 模式：关闭整个浏览器实例
			if self._browser:
				try:
					self._browser.close()
				except Exception:
					pass
		self._release_playwright()
		self._reset_channel_state()

	def _reset_channel_state(self) -> None:
		"""close 后把**通道标志**复位到「从未启动」。

		修既有缺陷：原实现只置 ``_started = False``，``_is_cdp`` / ``_is_bridge``
		留着上一轮的值。于是 close 之后再调 ``request()`` 会带着陈旧标志重跑整条链
		——例如上一轮走 Bridge、重连落到 CDP 时 ``_is_bridge`` 仍为 True，
		``request()`` 就会走错分支去调一个已被置空的 ``_bridge_client``。

		刻意**不**清 ``_page`` / ``_context`` / ``_browser``：它们在重启时由
		``_try_connect`` / ``_start_headless`` 的每个分支无条件覆盖，而清空会让
		「close 之后仍可检视上一轮句柄」这个既有性质消失（多条既有测试依赖它）。
		``_policy`` 同样不复位：它是构造期决定的来源意图，不属于通道状态。
		"""
		self._started = False
		self._is_cdp = False
		self._is_bridge = False

	def __enter__(self) -> "BrowserSession":
		return self

	def __exit__(
		self,
		exc_type: type[BaseException] | None,
		exc_val: BaseException | None,
		exc_tb: TracebackType | None,
	) -> None:
		self.close()


# ─── Raw CDP helper for evaluate_js ──────────────────────────────────────


def _pick_chat_target_ws(cdp_http_url: str) -> str:
	import json as _json
	import urllib.request

	list_url = cdp_http_url.rstrip("/") + "/json"
	try:
		with urllib.request.urlopen(list_url, timeout=3) as resp:
			tabs = _json.load(resp)
	except Exception as exc:
		raise RuntimeError(f"cannot reach CDP at {list_url}: {exc}") from exc

	for t in tabs:
		if t.get("type") == "page" and "/web/chat/index" in t.get("url", ""):
			target_ws = t.get("webSocketDebuggerUrl")
			if target_ws:
				return cast("str", target_ws)
	raise RecruiterChatTabRequired()


def _build_eval_expression(script: str, arg: Any) -> str:
	import json as _json

	if arg is not None:
		return f"({script})({_json.dumps(arg, ensure_ascii=False)})"
	return script


def _carve_utf8_bits(bs: bytes) -> list[str]:
	out: list[str] = []
	i = 0
	while i < len(bs):
		for length in range(min(len(bs) - i, 240), 4, -1):
			try:
				text = bs[i : i + length].decode("utf-8")
			except UnicodeDecodeError:
				continue
			if len(text) >= 5 and all(ch.isprintable() or ch in "\n\r\t" for ch in text):
				out.append(text)
				i += length
				break
		else:
			i += 1
	return out


def _cdp_evaluate_in_chat_tab(cdp_http_url: str, script: str, arg: Any) -> Any:
	"""Send Runtime.evaluate to the BOSS recruiter chat tab via raw CDP.

	Bypasses patchright entirely — avoids 'Frame was detached' errors when
	the Vue page re-renders during our call. Wraps the caller's script as
	`(fnSrc)(arg)` when arg is provided, so the script can be a JS expression
	that evaluates to a function of one argument (mirrors patchright's
	`page.evaluate(script, arg)` contract used by the PoC).
	"""
	import json as _json

	import websockets.sync.client as _ws_client

	target_ws = _pick_chat_target_ws(cdp_http_url)
	expression = _build_eval_expression(script, arg)

	with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
		ws.send(
			_json.dumps(
				{
					"id": 1,
					"method": "Runtime.evaluate",
					"params": {
						"expression": expression,
						"returnByValue": True,
						"awaitPromise": True,
					},
				}
			)
		)
		deadline = time.time() + 30.0
		while time.time() < deadline:
			raw = ws.recv(timeout=max(0.1, deadline - time.time()))
			msg = _json.loads(raw)
			if msg.get("id") != 1:
				continue
			err = msg.get("error")
			if err:
				raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
			result = msg.get("result", {}).get("result", {})
			if "value" in result:
				return result["value"]
			# Exception in JS side
			exc_details = msg.get("result", {}).get("exceptionDetails")
			if exc_details:
				raise RuntimeError(
					f"JS exception: {exc_details.get('text')} — {exc_details.get('exception', {}).get('description', '')[:300]}"
				)
			return result
		raise RuntimeError("CDP Runtime.evaluate timed out after 30s")


def _cdp_evaluate_with_chat_events_in_chat_tab(
	cdp_http_url: str, script: str, arg: Any, *, listen_ms: int
) -> dict[str, Any]:
	import base64 as _base64
	import json as _json

	import websockets.sync.client as _ws_client

	target_ws = _pick_chat_target_ws(cdp_http_url)
	expression = _build_eval_expression(script, arg)

	with _ws_client.connect(target_ws, max_size=8 * 1024 * 1024) as ws:
		ws.send(_json.dumps({"id": 1, "method": "Network.enable"}))
		ws.send(
			_json.dumps(
				{
					"id": 2,
					"method": "Runtime.evaluate",
					"params": {
						"expression": expression,
						"returnByValue": True,
						"awaitPromise": True,
					},
				}
			)
		)

		events: list[dict[str, Any]] = []
		eval_value: Any = None
		eval_done = False
		deadline = time.time() + 30.0
		listen_deadline: float | None = None

		while True:
			now = time.time()
			if eval_done and listen_deadline is not None and now >= listen_deadline:
				return {"value": eval_value, "events": events}
			if now >= deadline:
				raise RuntimeError("CDP Runtime.evaluate timed out after 30s")

			timeout = 0.1 if eval_done and listen_deadline is not None else max(0.1, deadline - now)
			try:
				raw = ws.recv(timeout=timeout)
			except TimeoutError:
				continue

			msg = _json.loads(raw)
			msg_id = msg.get("id")
			if msg_id == 2:
				err = msg.get("error")
				if err:
					raise RuntimeError(f"CDP Runtime.evaluate error: {err}")
				result = msg.get("result", {}).get("result", {})
				exc_details = msg.get("result", {}).get("exceptionDetails")
				if exc_details:
					raise RuntimeError(
						f"JS exception: {exc_details.get('text')} — "
						f"{exc_details.get('exception', {}).get('description', '')[:300]}"
					)
				eval_value = result.get("value", result)
				eval_done = True
				listen_deadline = time.time() + (listen_ms / 1000.0)
				continue

			method = msg.get("method")
			if method not in ("Network.webSocketFrameSent", "Network.webSocketFrameReceived"):
				continue
			frame = msg.get("params", {}).get("response", {})
			if frame.get("opcode") not in (1, 2):
				continue

			payload_data = frame.get("payloadData", "")
			try:
				bs = _base64.b64decode(payload_data, validate=False)
			except Exception:
				bs = payload_data.encode("utf-8", errors="ignore")
			if len(bs) < 30:
				continue

			events.append(
				{
					"ts": time.time(),
					"kind": "ws_send" if method.endswith("Sent") else "ws_recv",
					"bytes": len(bs),
					"utf8_bits": _carve_utf8_bits(bs)[:10],
				}
			)
